/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.13
 * Generated at: 2024-12-18 07:10:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Vue;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class addHotel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Ajouter un Hôtel - Formulaire Élégant</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&family=Open+Sans:wght@400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --color-primary: #4a6cf7;\r\n");
      out.write("            --color-secondary: #6b7aff;\r\n");
      out.write("            --color-background: #f4f7ff;\r\n");
      out.write("            --color-text-dark: #2c3036;\r\n");
      out.write("            --color-text-light: #6b7280;\r\n");
      out.write("            --shadow-subtle: 0 10px 30px rgba(0, 0, 0, 0.05);\r\n");
      out.write("            --shadow-hover: 0 15px 40px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            --transition-smooth: all 0.3s cubic-bezier(0.25, 0.1, 0.25, 1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Open Sans', sans-serif;\r\n");
      out.write("            background: var(--color-background);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            box-shadow: var(--shadow-subtle);\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 700px;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            transform: perspective(1000px) rotateX(-10deg);\r\n");
      out.write("            opacity: 0.9;\r\n");
      out.write("            transition: var(--transition-smooth);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container:hover {\r\n");
      out.write("            transform: perspective(1000px) rotateX(0);\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("            box-shadow: var(--shadow-hover);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-header {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-header h1 {\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            color: var(--color-primary);\r\n");
      out.write("            font-size: 2.2rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-header p {\r\n");
      out.write("            color: var(--color-text-light);\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(2, 1fr);\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group label {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            color: var(--color-text-dark);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            transition: var(--transition-smooth);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group label i {\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            color: var(--color-primary);\r\n");
      out.write("            opacity: 0.7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group input, \r\n");
      out.write("        .form-group textarea {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px 15px;\r\n");
      out.write("            border: 2px solid #e5e7eb;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            transition: var(--transition-smooth);\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group input:focus, \r\n");
      out.write("        .form-group textarea:focus {\r\n");
      out.write("            border-color: var(--color-primary);\r\n");
      out.write("            box-shadow: 0 0 0 3px rgba(74, 108, 247, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group.full-width {\r\n");
      out.write("            grid-column: span 2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .submit-section {\r\n");
      out.write("            grid-column: span 2;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .submit-btn {\r\n");
      out.write("            background: var(--color-primary);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 15px 40px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: var(--transition-smooth);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .submit-btn:hover {\r\n");
      out.write("            background: var(--color-secondary);\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .form-grid {\r\n");
      out.write("                grid-template-columns: 1fr;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-group.full-width,\r\n");
      out.write("            .submit-section {\r\n");
      out.write("                grid-column: span 1;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"form-container\">\r\n");
      out.write("        <div class=\"form-header\">\r\n");
      out.write("            <h1>Ajouter un Hôtel</h1>\r\n");
      out.write("            <p>Remplissez les détails de votre établissement avec soin</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Ajouterservlethotel\" method=\"post\" enctype=\"multipart/form-data\" class=\"form-grid\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"name\"><i class=\"fas fa-building\"></i>Nom de l'Hôtel</label>\r\n");
      out.write("                <input type=\"text\" id=\"name\" name=\"name\" placeholder=\"Ex: Grand Palace Resort\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"city\"><i class=\"fas fa-map-marker-alt\"></i>Ville</label>\r\n");
      out.write("                <input type=\"text\" id=\"city\" name=\"city\" placeholder=\"Ex: Paris\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"stars\"><i class=\"fas fa-star\"></i>Nombre d'Étoiles</label>\r\n");
      out.write("                <input type=\"number\" id=\"stars\" name=\"stars\" min=\"1\" max=\"5\" placeholder=\"1-5\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"image\"><i class=\"fas fa-image\"></i>Image de l'Hôtel</label>\r\n");
      out.write("                <input type=\"file\" id=\"image\" name=\"image\" accept=\"image/*\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group full-width\">\r\n");
      out.write("                <label for=\"description\"><i class=\"fas fa-pen\"></i>Description</label>\r\n");
      out.write("                <textarea id=\"description\" name=\"description\" placeholder=\"Décrivez votre hôtel en détail...\" rows=\"5\" required></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"submit-section\">\r\n");
      out.write("                <button type=\"submit\" class=\"submit-btn\">\r\n");
      out.write("                    <i class=\"fas fa-plus\"></i>Ajouter l'Hôtel\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
